ktor:
  application:
    modules:
      - com.example.plugins.ApplicationKt.module
  deployment:
    port: 8080
    host: "176.124.207.251"
postgres:
  url: "jdbc:postgresql://176.124.207.251:5432/db"
  user: bob
  password: vovan123A
  passwordjwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
