ktor:
  application:
    modules:
      - com.example.plugins.ApplicationKt.module
  deployment:
    port: 8081
    host: "0.0.0.0"
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password:
    passwordjwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
