ktor:
  application:
    modules:
      - com.example.plugins.ApplicationKt.module
  deployment:
    port: 8080
    host: "0.0.0.0"
postgres:
  url: "jdbc:postgresql://127.0.0.1/db"
  user: bob
  password: vovan123A
  passwordjwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
